version: 2

models:
  - name: dim_listings_cleansed
    descriptoin: This model is a cleaned version of the listings table
    columns:
      - name: room_type
        description: The type of room that is being listed
      
        data_tests:
          - accepted_values:
              values: ['Entire home/apt',
                        'Private room',
                        'Shared room',
                        'Hotel room']
      - name: listing_id
        description: >
          The unique identifier for the listing, also make sure it is not null
        data_tests:
          - unique
          - not_null

      - name: host_id
        data_tests:
          - not_null    
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: minimum_nights
        description: '{{ doc("dim_listings_cleansed_minimum_nights") }}'
        data_tests:
          - positive_valued